# Generated by Django 4.2.6 on 2023-10-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_sentence', models.TextField()),
            ],
        ),
    ]
